### PR TITLE
Use ei.h instead of erl_interface.h

### LINKED ISSUE #8: OTP 23 Not supported
Good day,

`erl_interface.h` was removed in OTP 23 causing compilation to fail

Looking at the examples for Erl_Interface I was able to get it working again by changing `libsodium_drv_common.h` to include <ei.h> instead, and removing `-lerl_interface` from the Makefile.

I'm not familiar with C or ports, so i'm unsure of the breadth of consequences of this, and would appreciate more experienced eyes on this.

One test currently fails but it's a function I don't use and am unfamiliar with: https://travis-ci.com/github/dabaer/erlang-libsodium/jobs/342993783

### PR DESCRIPTION
**Pull request by michaelklishin**
erl_interface.h has been removed in Erlang 23.

I think it's reasonable to require Erlang 23+ in modern releases. A lot of users are jumping to Erlang 24
because of the JIT.
So I suggest that we establish 23 as the new baseline version.

Closes #8.

### CODE REVIEW

**Comment by michaelklishin** [comment]
@potatosalad @ericmj  sorry to bother you with a direct mention but addressing and merging this is important for making progress on

 * https://github.com/potatosalad/erlang-jose/issues/113
 * https://github.com/potatosalad/erlang-jose/issues/114

because this library is a dependency that's compiled from source during test runs. Let me know what you think, I'm
keen on making Erlang 24 a first class citizen for `erlang-jose` :)

**Comment by michaelklishin** [comment]
Travis failures have to do with Dockerhub request limits as far as I can tell. I can try converting to Actions but it feels a bit out of scope for this PR :/

**Comment by michaelklishin** [comment]
It can be that Travis fetches `.travis.yml` from this repo and not my branch, which would explain why the mirror isn't used.

FWIW, all tests pass for me locally:

```
TEST INFO: 1 test(s), 12 case(s) in 1 suite(s)

Testing git.erlang-libsodium.libsodium_SUITE: Starting test, 12 test cases
[  ] 2021-06-10 03:44:34.072068 :: aead_aes256gcm
[OK] 2021-06-10 03:44:34.481835 :: 00:00:00.409767 elapsed
[  ] 2021-06-10 03:44:34.507526 :: aead_chacha20poly1305
[OK] 2021-06-10 03:44:34.571820 :: 00:00:00.064294 elapsed
[  ] 2021-06-10 03:44:34.604048 :: box
[OK] 2021-06-10 03:44:34.666199 :: 00:00:00.062151 elapsed
[  ] 2021-06-10 03:44:34.695734 :: pwhash
[OK] 2021-06-10 03:44:34.945569 :: 00:00:00.249835 elapsed
[  ] 2021-06-10 03:44:34.974622 :: pwhash_scrypt
[OK] 2021-06-10 03:44:35.625735 :: 00:00:00.651113 elapsed
[  ] 2021-06-10 03:44:35.652579 :: sign....
[OK] 2021-06-10 03:44:40.063355 :: 00:00:04.410776 elapsed
=INFO REPORT==== 9-Jun-2021::20:44:40.094063 ===
    application: libsodium
    exited: stopped
    type: temporary

Testing git.erlang-libsodium.libsodium_SUITE: TEST COMPLETE, 12 ok, 0 failed of 12 test cases
```

**Comment by ericmj** [comment]
> sorry to bother you with a direct mention but addressing and merging this is important for making progress on

I don't have access to this repo so unfortunately I cannot help you with merging or the CI errors.

Is this blocking getting erlang-jose to run OTP 24? It fails even when you run the tests on docker?

**Comment by michaelklishin** [comment]
> Is this blocking getting erlang-jose to run OTP 24? It fails even when you run the tests on docker?

it is because this project cannot be built from source on Erlang 23+.

**Comment by ericmj** [comment]
> it is because this project cannot be built from source on Erlang 23+.

erlang-jose CI is passing on OTP 23.

**Comment by michaelklishin** [comment]
Maybe it depends on a binary release but `mix test` compiles this project from source and that fails.

Anyhow, team RabbitMQ would really like to avoid forking this library. What can we do to get things Erlang 24-ready across
the board? The community is moving to 24 in large numbers, support of 22 or lower versions no longer seems to be
important in comparison.

**Comment by ericmj** [comment]
We may be able to drop OTP 22, but ideally I think we should try to support more than just two versions, one of which was newly released.

I can't help you move this PR in particular forward because I am not a maintainer of this repo and do not have commit access.

**Comment by michaelklishin** [comment]
The easiest option for Erlang 22 users would be to use an older tag/branch.

**Comment by sgessa** [comment]
Any news on this?

**Comment by ericmj** [comment]
No, there has been no other updates than what you see in this PR.

**Pull request merged**
